language: cpp
sudo: true
services:
  - docker
matrix:
  include:
    - os: linux
      env:
        - MATRIX_IMAGE="gcc:7.3.0"
    - os: linux
      env:
        - MATRIX_IMAGE="purplekarrot/clang-5.0"
before_install:
    - docker pull ${MATRIX_IMAGE}
script:
    - docker run --rm -v $(pwd):/opt/cotila -w /opt/cotila --entrypoint "" ${MATRIX_IMAGE} /bin/bash -c '/usr/bin/make clean && /usr/bin/make test'
